/*
 * Content shape: each round item has id, difficulty, material, correctAnswer,
 * technique, explanation, and fabricated. Material contains only what that
 * round renders; correctAnswer stays separate so future public snapshots can omit it.
 *
 * chainOfCustody is the optional bonus round. Its material holds the original
 * claim and four retellings in the shuffled order the screen shows them, each
 * with a short note naming what changed at that step. correctAnswer lists the
 * retelling ids from earliest to latest.
 */

export const englishContent = {
  locale: 'en',
  rounds: {
    oddSourceOut: [
      {
        id: 'odd-bridge-01',
        difficulty: 'easy',
        material: {
          event: 'A city opens a new pedestrian bridge',
          sources: [
            { id: 'a', label: 'A', source: 'Civic Design Review', headline: 'Early footfall data suggests modest gains near the new crossing' },
            { id: 'b', label: 'B', source: 'The Daily Megaphone', headline: 'BRIDGE CHANGES EVERYTHING AND OFFICIALS WILL NOT TELL YOU WHY' },
            { id: 'c', label: 'C', source: 'Harbour News', headline: 'Riverside footbridge opens after council safety inspection' },
            { id: 'd', label: 'D', source: 'The Slightly Bent Times', headline: 'Pigeons demand toll rights after bridge opens without consultation' },
          ],
        },
        correctAnswer: 'b',
        technique: 'Missing Attribution',
        explanation: 'The claim names no source, date, study, or official who could be checked.',
        fabricated: true,
      },
      {
        id: 'odd-library-02',
        difficulty: 'medium',
        material: {
          event: 'A library extends its weekend hours',
          sources: [
            { id: 'a', label: 'A', source: 'Public Services Quarterly', headline: 'Weekend access may improve attendance, though longer observation is needed' },
            { id: 'b', label: 'B', source: 'Town Record', headline: 'Central library adds Sunday hours from 4 May' },
            { id: 'c', label: 'C', source: 'Truth Torch Online', headline: 'THEY WANT YOU INSIDE ALL WEEKEND. ASK YOURSELF WHY.' },
            { id: 'd', label: 'D', source: 'The Paper Bookmark', headline: 'Books reportedly thrilled to lose their only quiet day' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Emotional Framing',
        explanation: 'The post substitutes suspicion and capital letters for evidence someone could verify.',
        fabricated: true,
      },
      {
        id: 'odd-garden-03',
        difficulty: 'hard',
        material: {
          event: 'A school plants a vegetable garden',
          sources: [
            { id: 'a', label: 'A', source: 'Learning Research Notes', headline: 'Small garden programmes correlate with engagement but do not prove wider attainment gains' },
            { id: 'b', label: 'B', source: 'Education Desk', headline: 'Northfield School opens teaching garden, 12 September' },
            { id: 'c', label: 'C', source: 'Unfiltered School Secrets', headline: 'EXPOSED: VEGETABLE PLOT WILL TRANSFORM EVERY CHILD OVERNIGHT' },
            { id: 'd', label: 'D', source: 'The Daily Trowel', headline: 'Carrots enrol early after school lowers roots requirement' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Unverifiable Certainty',
        explanation: 'A sweeping promise is presented without evidence, attribution, or a measurable definition of success.',
        fabricated: true,
      },
      {
        id: 'odd-battery-04',
        difficulty: 'easy',
        material: {
          event: 'A technology lab tests a sodium battery prototype',
          sources: [
            { id: 'a', label: 'A', source: 'Energy Materials Journal', headline: 'Prototype cell delivers 160 Wh/kg in room-temperature test cycles' },
            { id: 'b', label: 'B', source: 'Clean Grid Report', headline: 'Engineers report steady performance in early sodium chemistry trials' },
            { id: 'c', label: 'C', source: 'The Radical Wire', headline: 'MIRACLE BATTERY WILL CRUSH ALL OIL COMPANIES BY NEXT WEEK' },
            { id: 'd', label: 'D', source: 'The Spark & Plug', headline: 'AA batteries demand early retirement before sodium revolution arrives' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Sensational Hyperbole',
        explanation: 'Early lab benchmarks are exaggerated into a guaranteed overnight industrial revolution without proof.',
        fabricated: true,
      },
      {
        id: 'odd-coffee-05',
        difficulty: 'medium',
        material: {
          event: 'A health institute updates daily caffeine guidelines',
          sources: [
            { id: 'a', label: 'A', source: 'Clinical Nutrition Review', headline: 'Moderate intake of 3 to 4 cups shows no adverse heart markers in meta-analysis' },
            { id: 'b', label: 'B', source: 'Public Health Weekly', headline: 'Panel recommends capping caffeine at 400mg daily for healthy adults' },
            { id: 'c', label: 'C', source: 'Secret Body Hacks', headline: 'DOCTORS HATE THIS: DRINKING 9 ESPRESSOS MELTS TOXINS INSTANTLY' },
            { id: 'd', label: 'D', source: 'The Roasted Onion', headline: 'Local cat demands third cappuccino to get through morning nap' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Dangerous Pseudo-Science',
        explanation: 'The headline makes an extreme medical health claim while attacking doctors rather than citing evidence.',
        fabricated: true,
      },
      {
        id: 'odd-transit-06',
        difficulty: 'hard',
        material: {
          event: 'A transit authority rolls out tap-to-pay bus cards',
          sources: [
            { id: 'a', label: 'A', source: 'Municipal Transit Gazette', headline: 'Contactless payment active across all 42 city bus routes starting Monday' },
            { id: 'b', label: 'B', source: 'Urban Logistics Report', headline: 'Boarding dwell times decreased 14 percent in pilot terminal tests' },
            { id: 'c', label: 'C', source: 'Truth Alert Broadcast', headline: 'THEY ARE USING TAP CARDS TO MONITOR YOUR THOUGHTS AND DIET' },
            { id: 'd', label: 'D', source: 'The Turnstile Chronicle', headline: 'Old paper tickets demand museum exhibition to preserve dignity' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Paranoid Projection',
        explanation: 'Standard ticketing technology is framed as an omnipotent mind-control system with zero substantiation.',
        fabricated: true,
      },
      {
        id: 'odd-space-07',
        difficulty: 'medium',
        material: {
          event: 'An observatory catalogues a near-Earth asteroid',
          sources: [
            { id: 'a', label: 'A', source: 'Astrophysical Journal Letters', headline: 'Trajectory calculations place 2026-XB passing 4.2 lunar distances away' },
            { id: 'b', label: 'B', source: 'Sky & Telescope Digest', headline: 'Amateur observers confirm orbital coordinates for 80-metre asteroid' },
            { id: 'c', label: 'C', source: 'End Times Dispatch', headline: 'DOOMSDAY ROCK TARGETING EARTH: NASA SILENT AND REFUSES TO DENY' },
            { id: 'd', label: 'D', source: 'The Cosmic Post', headline: 'Asteroid files formal noise complaint regarding Earth radio signals' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Manufactured Panic',
        explanation: 'A routine, distant flyby is converted into guaranteed catastrophe using a fake refusal-to-deny conspiracy trope.',
        fabricated: true,
      },
      {
        id: 'odd-school-08',
        difficulty: 'hard',
        material: {
          event: 'A school board pilots a four-day instructional week',
          sources: [
            { id: 'a', label: 'A', source: 'Education Policy Quarterly', headline: 'Four-day pilot shows stable test percentiles with slightly lengthened daily schedules' },
            { id: 'b', label: 'B', source: 'Valley School Board Record', headline: 'Pilot begins in September across five regional secondary schools' },
            { id: 'c', label: 'C', source: 'School Shock Underground', headline: 'TEACHERS SURRENDER: KIDS NEVER HAVE TO DO HOMEWORK OR MATH AGAIN' },
            { id: 'd', label: 'D', source: 'The Daily Eraser', headline: 'Fridays reportedly shocked to find out they are now part of the weekend' },
          ],
        },
        correctAnswer: 'c',
        technique: 'Absolutist Distortion',
        explanation: 'A structured scheduling experiment is distorted into a total collapse of curriculum and academic standards.',
        fabricated: true,
      },
    ],
    spinDoctor: [
      {
        id: 'spin-commute-01',
        difficulty: 'easy',
        material: {
          phrases: ['New survey finds', 'commuters are furious', 'after a tiny fare change', 'according to 42 online replies'],
        },
        correctAnswer: [1, 2, 3],
        technique: 'Loaded Language and Weak Sample',
        explanation: '“Furious” pushes emotion, while “tiny” judges the change and 42 online replies may not represent commuters.',
        fabricated: true,
      },
      {
        id: 'spin-lunch-02',
        difficulty: 'medium',
        material: {
          phrases: ['Experts agree', 'the new lunch menu is a triumph', 'after sales rose 18 percent', 'during opening week'],
        },
        correctAnswer: [0, 1, 3],
        technique: 'Missing Attribution and Context',
        explanation: 'The experts are unnamed, “triumph” is a judgement, and one opening week gives too little context.',
        fabricated: true,
      },
      {
        id: 'spin-park-03',
        difficulty: 'hard',
        material: {
          phrases: ['Critics attack', 'the bold park plan', 'despite most residents supporting it', 'in one neighbourhood poll'],
        },
        correctAnswer: [0, 1, 3],
        technique: 'Loaded Language and Cherry-Picked Evidence',
        explanation: '“Attack” and “bold” steer the reader, while one neighbourhood poll cannot stand for every resident.',
        fabricated: true,
      },
      {
        id: 'spin-tech-04',
        difficulty: 'easy',
        material: {
          phrases: ['Anonymous insiders claim', 'the radical software update', 'has completely failed', 'in preliminary internal trials'],
        },
        correctAnswer: [0, 1, 2],
        technique: 'Anonymous Attribution and Sweeping Verdicts',
        explanation: '“Anonymous insiders” cannot be audited, “radical” biases perception, and “completely failed” is an unmeasured absolute.',
        fabricated: true,
      },
      {
        id: 'spin-housing-05',
        difficulty: 'medium',
        material: {
          phrases: ['Officials celebrate', 'a massive development surge', 'after four permits were filed', 'on Tuesday morning'],
        },
        correctAnswer: [0, 1, 3],
        technique: 'Inflation of Minor Figures',
        explanation: '“Celebrate” and “massive development surge” inflate a tiny routine count of four permits on a single morning into a trend.',
        fabricated: true,
      },
      {
        id: 'spin-diet-06',
        difficulty: 'hard',
        material: {
          phrases: ['Influencers swear', 'this miracle superfood berry', 'melts waistline fat instantly', 'with zero side effects'],
        },
        correctAnswer: [0, 1, 2],
        technique: 'Pseudo-Scientific Hype',
        explanation: '“Influencers swear” replaces clinical trials, “miracle superfood” is marketing spin, and “melts fat instantly” is physiological nonsense.',
        fabricated: true,
      },
      {
        id: 'spin-sports-07',
        difficulty: 'medium',
        material: {
          phrases: ['Outraged fans demand', 'the disgraced coach resign immediately', 'following a narrow preseason loss', 'in a radio call-in show'],
        },
        correctAnswer: [0, 1, 3],
        technique: 'Voluntary Response Bias',
        explanation: '“Outraged fans” generalizes a self-selecting radio call-in show, while “disgraced” imposes an editorial verdict.',
        fabricated: true,
      },
      {
        id: 'spin-weather-08',
        difficulty: 'hard',
        material: {
          phrases: ['Terrified crowds flee', 'the catastrophic heatwave', 'as peak temperatures reach 29 degrees', 'in one sheltered garden'],
        },
        correctAnswer: [0, 1, 3],
        technique: 'Alarmist Microclimate Cherry-Picking',
        explanation: '“Terrified crowds flee” manufactures panic, “catastrophic” exaggerates mild summer weather, and one sheltered spot is unrepresentative.',
        fabricated: true,
      },
    ],
    realOrRendered: [
      {
        id: 'render-market-01',
        difficulty: 'easy',
        material: { kind: 'image-description', prompt: 'A market photograph where a hanging shop sign contains tangled, unreadable letters.' },
        correctAnswer: 'rendered',
        technique: 'Garbled Text',
        explanation: 'Text inside generated images often looks letter-like without forming stable words.',
        fabricated: true,
      },
      {
        id: 'render-notice-02',
        difficulty: 'medium',
        material: { kind: 'text', prompt: 'A council notice gives a department name, publication date, reference number, and a working contact route.' },
        correctAnswer: 'real',
        technique: 'Verifiable Specifics',
        explanation: 'Concrete details provide several independent paths for checking where the notice came from.',
        fabricated: true,
      },
      {
        id: 'render-station-03',
        difficulty: 'hard',
        material: { kind: 'image-description', prompt: 'A station crowd where the same scarf pattern repeats on six unrelated people.' },
        correctAnswer: 'rendered',
        technique: 'Repeating Background Detail',
        explanation: 'Synthetic scenes can repeat textures or objects where a real crowd would vary naturally.',
        fabricated: true,
      },
      {
        id: 'render-portrait-04',
        difficulty: 'medium',
        material: { kind: 'image-description', prompt: 'A portrait where one hand has six fingers and a bracelet merges into the wrist.' },
        correctAnswer: 'rendered',
        technique: 'Anatomy Mismatch',
        explanation: 'Extra fingers and objects melting into skin are strong signs that an image was synthesised.',
        fabricated: true,
      },
      {
        id: 'render-report-05',
        difficulty: 'hard',
        material: { kind: 'text', prompt: 'A short report names its dataset, links to the source, states its sample size, and explains a limitation.' },
        correctAnswer: 'real',
        technique: 'Checkable Sourcing',
        explanation: 'A named dataset, method, and limitation give a reader concrete claims to verify.',
        fabricated: true,
      },
      {
        id: 'render-press-06',
        difficulty: 'easy',
        material: { kind: 'text', prompt: 'A university lab press release lists lead researcher names, peer-reviewed journal volume, and funding disclosure.' },
        correctAnswer: 'real',
        technique: 'Institutional Transparency',
        explanation: 'Named researchers, published journal citations, and explicit funding grants allow immediate independent verification.',
        fabricated: true,
      },
      {
        id: 'render-clock-07',
        difficulty: 'easy',
        material: { kind: 'image-description', prompt: 'A photograph of a town square clock tower where the dial has numbers 1 through 15 scrambled.' },
        correctAnswer: 'rendered',
        technique: 'Nonsensical Dial Markings',
        explanation: 'Generative models frequently hallucinate non-standard numeric layouts and dial geometry.',
        fabricated: true,
      },
      {
        id: 'render-receipt-08',
        difficulty: 'medium',
        material: { kind: 'text', prompt: 'A grocery register receipt showing itemized purchases, 6 percent sales tax calculation, cashier ID, and timestamp.' },
        correctAnswer: 'real',
        technique: 'Mathematical and Transactional Consistency',
        explanation: 'Itemized totals, precise arithmetic tax match, and point-of-sale metadata provide concrete audit trails.',
        fabricated: true,
      },
      {
        id: 'render-reflection-09',
        difficulty: 'hard',
        material: { kind: 'image-description', prompt: 'A puddle reflection where a modern office glass tower reflects as an antique Gothic church spire.' },
        correctAnswer: 'rendered',
        technique: 'Inconsistent Reflection Physics',
        explanation: 'Synthetic imaging algorithms often hallucinate mismatched reflection geometry that contradicts the foreground scene.',
        fabricated: true,
      },
      {
        id: 'render-weather-10',
        difficulty: 'medium',
        material: { kind: 'text', prompt: 'A national meteorological radar map citing station buoy IDs, isobar millibar lines, and UTC radar timestamp.' },
        correctAnswer: 'real',
        technique: 'Standardized Scientific Notation',
        explanation: 'Official radar maps follow precise coordinate grids, station IDs, and UTC timing conventions.',
        fabricated: true,
      },
      {
        id: 'render-hands-11',
        difficulty: 'easy',
        material: { kind: 'image-description', prompt: 'A ceremony photo where the person on the left has two thumbs and a floating ring hovering in air.' },
        correctAnswer: 'rendered',
        technique: 'Floating Objects and Extra Digits',
        explanation: 'Floating artifacts and redundant thumbs are classic hallmarks of generative synthesis.',
        fabricated: true,
      },
      {
        id: 'render-museum-12',
        difficulty: 'hard',
        material: { kind: 'text', prompt: 'A museum catalog card displaying accession number, catalog date, provenance donor, and dimensions in cm.' },
        correctAnswer: 'real',
        technique: 'Archival Accession Metadata',
        explanation: 'Formal museum accession records contain specific cross-referencable catalog numbers and donor provenance history.',
        fabricated: true,
      },
    ],
    chainOfCustody: [
      {
        id: 'chain-bus-01',
        difficulty: 'easy',
        material: {
          claim: 'A transport office asks 300 riders about the timetable.',
          retellings: [
            { id: 'a', label: 'A', text: 'Riders are demanding a later last bus.', note: 'The number goes. A want becomes a demand.' },
            { id: 'b', label: 'B', text: 'A transport office survey of 300 riders found 6 in 10 want a later last bus.', note: 'Named source, sample size, measured finding.' },
            { id: 'c', label: 'C', text: 'EVERYONE IS FURIOUS THE LAST BUS IS SO EARLY.', note: 'Six in ten is now everyone. Wanting is now fury.' },
            { id: 'd', label: 'D', text: 'A survey says most riders want a later last bus.', note: 'The office and the sample size drop away.' },
          ],
        },
        correctAnswer: ['b', 'd', 'a', 'c'],
        technique: 'Detail Loss and Escalation',
        explanation: 'Each retelling drops a checkable detail and adds a stronger feeling, until a measured finding sounds like an outcry.',
        fabricated: true,
      },
      {
        id: 'chain-clinic-02',
        difficulty: 'medium',
        material: {
          claim: 'A clinic publishes its waiting times for the winter months.',
          retellings: [
            { id: 'a', label: 'A', text: 'Waiting at the clinic has doubled.', note: 'A three month change becomes permanent.' },
            { id: 'b', label: 'B', text: 'The clinic says waiting rose from 9 to 18 minutes between December and February.', note: 'Named source, both numbers, the period covered.' },
            { id: 'c', label: 'C', text: 'Waiting at the clinic doubled over the winter.', note: 'The starting number goes. Only doubled remains.' },
            { id: 'd', label: 'D', text: 'NOBODY IS SAFE AT THAT CLINIC ANY MORE.', note: 'Nine minutes becomes a danger to everyone.' },
          ],
        },
        correctAnswer: ['b', 'c', 'a', 'd'],
        technique: 'Missing Context and Inflation',
        explanation: 'Dropping the starting number and the season lets a small measured rise carry a much larger meaning.',
        fabricated: true,
      },
      {
        id: 'chain-reading-03',
        difficulty: 'hard',
        material: {
          claim: 'A school shares one year of reading results with parents.',
          retellings: [
            { id: 'a', label: 'A', text: 'A school found reading scores rose 4 percent in one year group after a reading hour.', note: 'One year group, one year, one number.' },
            { id: 'b', label: 'B', text: 'PROOF: ONE HOUR A DAY FIXES ANY CHILD.', note: 'One school, retold as every child.' },
            { id: 'c', label: 'C', text: 'Reading hours are working, schools report.', note: 'One school becomes schools. A link becomes a verdict.' },
            { id: 'd', label: 'D', text: 'A reading hour lifted scores at a school.', note: 'The year group and the 4 percent disappear.' },
          ],
        },
        correctAnswer: ['a', 'd', 'c', 'b'],
        technique: 'Scope Creep',
        explanation: 'Each step widens who the claim covers, from one year group to every child, with no new evidence.',
        fabricated: true,
      },
      {
        id: 'chain-solar-04',
        difficulty: 'easy',
        material: {
          claim: 'A lab trials a new solar panel coating under controlled lamps.',
          retellings: [
            { id: 'a', label: 'A', text: 'A lab test of 50 coated cells found average conversion efficiency rose 2.8 percent.', note: 'Named sample, lab conditions, precise 2.8 percent metric.' },
            { id: 'b', label: 'B', text: 'New solar panel coating boosts output, researchers say.', note: 'The 2.8 percent and laboratory setup disappear.' },
            { id: 'c', label: 'C', text: 'New panels produce vastly more energy than old technology.', note: 'Modest gain becomes vast superiority across all panels.' },
            { id: 'd', label: 'D', text: 'FREE ENDLESS POWER IS HERE AND ENERGY BILLS ARE DEAD FOREVER!', note: 'Lab trial escalates into guaranteed free power for the world.' },
          ],
        },
        correctAnswer: ['a', 'b', 'c', 'd'],
        technique: 'Progressive Exaggeration',
        explanation: 'A 2.8 percent efficiency gain in a lab environment is retold until it sounds like free global energy.',
        fabricated: true,
      },
      {
        id: 'chain-traffic-05',
        difficulty: 'medium',
        material: {
          claim: 'A transit department studies vehicle flow during road repairs.',
          retellings: [
            { id: 'a', label: 'A', text: 'Morning bridge crossings averaged 4 minutes longer during weekday repaving.', note: 'Specific 4-minute figure, weekday constraint, specific cause.' },
            { id: 'b', label: 'B', text: 'Bridge traffic slowed down during the road resurfacing project.', note: 'Exact 4 minutes drops away; generic slowdown remains.' },
            { id: 'c', label: 'C', text: 'Bridge delays are paralyzing the entire city every single day.', note: 'Weekday repaving becomes citywide daily paralysis.' },
            { id: 'd', label: 'D', text: 'TOTAL GRIDLOCK: NOBODY WILL EVER GET TO WORK ON TIME AGAIN!', note: 'Minor delay escalates into hopeless municipal collapse.' },
          ],
        },
        correctAnswer: ['a', 'b', 'c', 'd'],
        technique: 'Geographic and Emotional Inflation',
        explanation: 'A four-minute delay on one road is exaggerated into a permanent citywide crisis.',
        fabricated: true,
      },
      {
        id: 'chain-water-06',
        difficulty: 'hard',
        material: {
          claim: 'A municipal water board tests reservoir clarity after heavy rain.',
          retellings: [
            { id: 'a', label: 'A', text: 'Water board samples across 16 reservoir sites showed turbidity within safety margins.', note: 'Sample site count, measured turbidity parameter, safety threshold.' },
            { id: 'b', label: 'B', text: 'Officials say tap water remains safe following heavy rain.', note: 'Sample counts and turbidity specifics drop.' },
            { id: 'c', label: 'C', text: 'Officials claim reservoir water is fine despite visible cloudiness.', note: 'Scepticism and suspicion are injected into a clean report.' },
            { id: 'd', label: 'D', text: 'POISON COVERUP: CITY TAPS ARE CONTAMINATED AND DANGEROUS!', note: 'A passing safety test is flipped into a deadly conspiracy.' },
          ],
        },
        correctAnswer: ['a', 'b', 'c', 'd'],
        technique: 'Inversion into Conspiracy',
        explanation: 'A compliant water test loses its technical metrics and is inverted into an intentional cover-up.',
        fabricated: true,
      },
    ],
  },
}

export default englishContent
